### ISSUE TITLE
Can't disable wasm-opt for a workspace package

### ISSUE THREAD

**Issue by cvermilion** [bytecodealliance/cargo-wasi#141]
Demo repo here: https://github.com/remixlabs/wasm-opt-bug.

As far as I can tell, setting `wasm-opt = false` in `Cargo.toml` as [described here](https://bytecodealliance.github.io/cargo-wasi/config.html) works for a standalone package, but not for a workspace package.

Things I've tried:

```toml
# in package's Cargo.toml
[package.metadata]
wasm-opt = false
```

```toml
# in workspace's Cargo.toml
[package.metadata]
wasm-opt = false
```

```toml
# in workspace's Cargo.toml
[workspace.package.metadata]
wasm-opt = false
```

```toml
# in workspace's Cargo.toml
[workspace.metadata]
wasm-opt = false
```

None seem to disable `wasm-opt` when building in release mode. (The "Optimizing with wasm-opt" log line is still printed, and the output size is the optimized size.)

See the linked repo above for more details.
